#!/bin/bash

###################################################################################################################
#                                                                                                                 #
# Returns the cheapest quotes that meet this query. The prices come from skyscanner's cached prices resulting     #
# from their users’ searches.                                                                                     #
#                                                                                                                 #
# Register for apikey here: http://portal.business.skyscanner.net/en-gb/accounts/login/                           #
#                                                                                                                 #
# -co={country}                                                                                                   #
# -cu={currency}                                                                                                  #
# -lo={locale}                                                                                                    #
# -orp={origin place}                                                                                             #
# -dep={destination place}                                                                                        #
# -oupd={outbound partial date}                                                                                   #
# -inpd={inbound partial date}     <- not compulsory                                                              #
# -apk={SkyScanner API key}                                                                                       #
#                                                                                                                 #
# usage:                                                                                                          #
# 	~$ ./browse_quotes -co=HU -cu=HUF -lo=hu-HU -orp=BUDA -dep=LOND -oupd=2017-05 -inpd=2017-05 -apk={apikey}     #
#                                                                                                                 #
###################################################################################################################


##### Functions

unwrap_quotes()
{
    # creating csv table from quotes.json
    infile=$1
    outfile=$2
    jq '.Quotes[]? | {
	"QuoteId": (.QuoteId | tostring),
	"MinPrice": (.MinPrice | tostring),
	"Direct": (.Direct | tostring),
	"OutboundLegCarrierIds": (.OutboundLeg.CarrierIds[]? | tostring),
	"OutboundLegOriginId": (.OutboundLeg.OriginId | tostring),
	"OutboundLegDestinationId": (.OutboundLeg.DestinationId | tostring),
	"OutboundLegDepartureDate": .OutboundLeg.DepartureDate,
	"InboundLegCarrierIds": (.InboundLeg.CarrierIds[]? | tostring),
	"InboundLegOriginId": (.InboundLeg.OriginId | tostring),
	"InboundLegDestinationId": (.InboundLeg.DestinationId | tostring),
	"InboundLegDepartureDate": .InboundLeg.DepartureDate,
	"QuoteDateTime": .QuoteDateTime
	} | join("¤")' $infile  > tmp1.csv
	awk '!v[$1]++' tmp1.csv > $outfile
	sed -i 's/¤/";"/g' $outfile
	sed -i 1i'"QuoteId";"MinPrice";"Direct";"OL_CarrierIds";"OL_OriginId";"OL_DestinationId";"OL_DepartureDate";"IL_CarrierIds";"IL_OriginId";"IL_DestinationId";"IL_DepartureDate";"QuoteDateTime"' $outfile
	rm -f tmp1.csv
	unset infile
	unset outfile
}

unwrap_places()
{
	# creating Places level csv table from quotes.json
	infile=$1
    outfile=$2
	jq '.Places[]? | {
	"PlaceId": (.PlaceId | tostring),
	"PlaceIataCode": .IataCode,
	"PlaceName": .Name,
	"PlaceType": .Type
	} | join("¤")' $infile  > tmp2.csv
	awk '!v[$1]++' tmp2.csv > $outfile
	sed -i 's/¤/";"/g' $outfile
	sed -i 1i'"PlaceId";"PlaceIataCode";"PlaceName";"PlaceType"' $outfile
	rm -f tmp2.csv
	unset infile
	unset outfile
}

unwrap_carriers()
{
	# creating Carriers level csv table from quotes.json
	infile=$1
    outfile=$2
	jq '.Carriers[]? | {
	"CarrierId": (.CarrierId | tostring),
	"CarrierName": .Name
	} | join("¤")' $infile  > tmp3.csv
	awk '!v[$1]++' tmp3.csv > $outfile
	sed -i 's/¤/";"/g' $outfile
	sed -i 1i'"CarrierId";"CarrierName"' $outfile
	rm -f tmp3.csv
	unset infile
	unset outfile
}

unwrap_currencies()
{
	# creating Currencies level csv table from quotes.json
	infile=$1
    outfile=$2
	jq '.Currencies[]? | {
	"CurrencyCode": .Code,
	"CurrencySymbol": .Symbol,
	"CurrencyThousandsSeparator": .ThousandsSeparator,
	"CurrencyDecimalSeparator": .DecimalSeparator
	} | join("¤")' $infile  > tmp4.csv
	awk '!v[$1]++' tmp4.csv > $outfile
	sed -i 's/¤/";"/g' $outfile
	sed -i 1i'"CurrencyCode";"CurrencySymbol";"CurrencyThousandsSeparator";"CurrencyDecimalSeparator"' $outfile
	rm -f tmp4.csv
	unset infile
	unset outfile
}


##### Main

# the following arguments should be provided by the user of this bash script
for i in "$@"
do
	case $i in
		-co=*|--country=*)
			Country="${i#*=}"
			shift # past argument=value
		;;
		-cu=*|--currency=*)
			Currency="${i#*=}"
			shift # past argument=value
		;;
		-lo=*|--locale=*)
			Locale="${i#*=}"
			shift # past argument=value
		;;
		-orp=*|--originplace=*)
			OriginPlace="${i#*=}"
			shift # past argument=value
		;;
		-dep=*|--destinationplace=*)
			DestinationPlace="${i#*=}"
			shift # past argument=value
		;;
		-oupd=*|--outboundpartialdate=*)
			OutboundPartialDate="${i#*=}"
			shift # past argument=value
		;;
		-inpd=*|--inboundpartialdate=*)
			InboundPartialDate="${i#*=}"
			shift # past argument=value
		;;
		-apk=*|--apikey=*)
			ApiKey="${i#*=}"
			shift # past argument=value
		;;
		*)
			# unknown option
		;;
	esac
done
wait

# composing download link 1st part with arguments
link1="http://partners.api.skyscanner.net/apiservices/browsequotes/v1.0/"${Country}"/"${Currency}"/"${Locale}"/"${OriginPlace}"/"${DestinationPlace}"/"${OutboundPartialDate}

# composing download link 2nd part with an arguments
link2="/"${InboundPartialDate}
length=${#link2}
case "$length" in
	1) link2="" ;;
	esac

# composing download link 3rd part with an argument
link3="?ApiKey="${ApiKey}
length=${#link3}
case "$length" in
	8) link3="?ApiKey="$(grep -w "Insiprational_Flights" ~/Documents/creds.csv | cut -d "," -f3) ;;
	esac 

# composing download links with arguments from all parts
link=$link1$link2$link3	

# creating a data folder 
if [ ! -d "./data" ]; then
  mkdir ./data
fi
cd ./data

# downloading json file
#curl -sL $link > quotes.json
wget -q $link -O quotes.json

# creating csv table from quotes.json
unwrap_quotes quotes.json quotes.csv &

# creating Places level csv table from quotes.json
unwrap_places quotes.json places.csv &

# creating Currencies level csv table from quotes.json
unwrap_currencies quotes.json currencies.csv &

# creating Carriers level csv table from quotes.json
unwrap_carriers quotes.json carriers.csv &

# waiting for concurent processes to be finished (denoted with & ampersand)
wait

# let us join Quotes and OutboundLeg_Origin 
csvjoin --delimiter ';' -u 1 -c "OL_OriginId, PlaceId" --left quotes.csv places.csv | sed -r 's/[^,]+/"&"/g' | sed 's/\,/;/g' > tmp.csv

# renaming columns
sed -i '1s/.*/QuoteId;MinPrice;Direct;OL_CarrierIds;OL_OriginId;OL_DestinationId;OL_DepartureDate;IL_CarrierIds;IL_OriginId;IL_DestinationId;IL_DepartureDate;QuoteDateTime;OL_OriginIataCode;OL_OriginName;OL_OriginType/' tmp.csv

# let us join Quotes and OutboundLeg_Destination
csvjoin --delimiter ';' -u 1 -c "OL_DestinationId, PlaceId" --left tmp.csv places.csv | sed -r 's/[^,]+/"&"/g' | sed 's/\,/;/g' > quotes.csv
# renaming columns
sed -i '1s/.*/QuoteId;MinPrice;Direct;OL_CarrierIds;OL_OriginId;OL_DestinationId;OL_DepartureDate;IL_CarrierIds;IL_OriginId;IL_DestinationId;IL_DepartureDate;QuoteDateTime;OL_OriginIataCode;OL_OriginName;OL_OriginType;OL_DestinationIataCode;OL_DestinationName;OL_DestinationType/' quotes.csv

# let us join Quotes and InboundLeg_OriginId
csvjoin --delimiter ';' -u 1 -c "IL_OriginId, PlaceId" --left quotes.csv places.csv | sed -r 's/[^,]+/"&"/g' | sed 's/\,/;/g' > tmp.csv
# renaming columns
sed -i '1s/.*/QuoteId;MinPrice;Direct;OL_CarrierIds;OL_OriginId;OL_DestinationId;OL_DepartureDate;IL_CarrierIds;IL_OriginId;IL_DestinationId;IL_DepartureDate;QuoteDateTime;OL_OriginIataCode;OL_OriginName;OL_OriginType;OL_DestinationIataCode;OL_DestinationName;OL_DestinationType;IL_OriginIataCode;IL_OriginName;IL_OriginType/' tmp.csv

# let us join Quotes and InboundLeg_Destination
csvjoin --delimiter ';' -u 1 -c "IL_DestinationId, PlaceId" --left tmp.csv places.csv | sed -r 's/[^,]+/"&"/g' | sed 's/\,/;/g' > quotes.csv
# renaming columns
sed -i '1s/.*/QuoteId;MinPrice;Direct;OL_CarrierIds;OL_OriginId;OL_DestinationId;OL_DepartureDate;IL_CarrierIds;IL_OriginId;IL_DestinationId;IL_DepartureDate;QuoteDateTime;OL_OriginIataCode;OL_OriginName;OL_OriginType;OL_DestinationIataCode;OL_DestinationName;OL_DestinationType;IL_OriginIataCode;IL_OriginName;IL_OriginType;IL_DestinationIataCode;IL_DestinationName;IL_DestinationType/' quotes.csv  

# let us join Quotes and OutboundLeg_Carrier
csvjoin --delimiter ';' -u 1 -c "OL_CarrierIds, CarrierId" --left quotes.csv carriers.csv | sed -r 's/[^,]+/"&"/g' | sed 's/\,/;/g' > tmp.csv
# renaming columns
sed -i '1s/.*/QuoteId;MinPrice;Direct;OL_CarrierIds;OL_OriginId;OL_DestinationId;OL_DepartureDate;IL_CarrierIds;IL_OriginId;IL_DestinationId;IL_DepartureDate;QuoteDateTime;OL_OriginIataCode;OL_OriginName;OL_OriginType;OL_DestinationIataCode;OL_DestinationName;OL_DestinationType;IL_OriginIataCode;IL_OriginName;IL_OriginType;IL_DestinationIataCode;IL_DestinationName;IL_DestinationType;OL_CarrierName/' tmp.csv

# let us join Quotes and InboundLeg_Carrier
csvjoin --delimiter ';' -u 1 -c "IL_CarrierIds, CarrierId" --left tmp.csv carriers.csv | sed -r 's/[^,]+/"&"/g' | sed 's/\,/;/g' > quotes.csv
# renaming columns
sed -i '1s/.*/QuoteId;MinPrice;Direct;OL_CarrierIds;OL_OriginId;OL_DestinationId;OL_DepartureDate;IL_CarrierIds;IL_OriginId;IL_DestinationId;IL_DepartureDate;QuoteDateTime;OL_OriginIataCode;OL_OriginName;OL_OriginType;OL_DestinationIataCode;OL_DestinationName;OL_DestinationType;IL_OriginIataCode;IL_OriginName;IL_OriginType;IL_DestinationIataCode;IL_DestinationName;IL_DestinationType;OL_CarrierName;IL_CarrierName/' quotes.csv

# creating new output filename by adding direction and date to the name of the result file
dt=$(date '+%Y%m%d_%H%M%S')
outfile="quotes_"$OriginPlace"_"$DestinationPlace"_"$dt".csv"

# extracting currency related values into variables
Code=$(awk -F';' -v line=2 -v field=1 'NR==line{print $field}' currencies.csv)
Symbol=$(awk -F';' -v line=2 -v field=2 'NR==line{print $field}' currencies.csv)
CurrencyThousandsSeparator=$(awk -F';' -v line=2 -v field=3 'NR==line{print $field}' currencies.csv)
CurrencyDecimalSeparator=$(awk -F';' -v line=2 -v field=4 'NR==line{print $field}' currencies.csv)

# adding currency related columns
awk -F';' -v OFS=';' -v Sym="${Symbol}" -v Cod="${Code}" -v Tho="${CurrencyThousandsSeparator}" -v Dec="${CurrencyDecimalSeparator}" '{print $1, $2, Sym, $3, $12, $4, $25, $14, $15, $5, $13, $7, $6, $17, $18, $16, $8, $26, $20, $21, $9, $19, $11, $10, $22, $23, $24, Cod, Tho, Dec}' quotes.csv > $outfile

# renaming columns
sed -i '1s/.*/QuoteId;MinPrice;Symbol;Direct;QuoteDateTime;OL_CarrierId;OL_CarrierName;OL_OriginName;OL_OriginType;OL_OriginId;OL_OriginIataCode;OL_DepartureDate;OL_DestinationId;OL_DestinationName;OL_DestinationType;OL_DestinationIataCode;IL_CarrierId;IL_CarrierName;IL_OriginName;IL_OriginType;IL_OriginId;IL_OriginIataCode;IL_DepartureDate;IL_DestinationId;IL_DestinationIataCode;IL_DestinationName;IL_DestinationType;Code;ThousandsSeparator;DecimalSeparator/' $outfile

# let's show the results on screen
# cat $outfile | csvlook

# removing intermediary files
rm -f quotes.json quotes.csv tmp.csv places.csv carriers.csv currencies.csv
unset dt
unset infile
unset outfile
